#!/bin/bash

javac -cp /opt/minecraft/Spigot/Spigot-API/target/spigot-api-$MINECRAFT_VERSION-R0.1-SNAPSHOT-shaded.jar plugin/org/wwlib/spigotmc/HelloJavaScript/Main.java

jar cvf hellojavascript.jar -C plugin .

cp hellojavascript.jar /minecraft/plugins/hellojavascript.jar