#!/bin/bash

if [ -d "/minecraft" ]; then
  echo "Directory /minecraft exists."
  cd /minecraft
 if [ -f "server.properties" ]; then
  echo "server.properties exists"
  else
    echo "server.properties does not exist. Copying from /opt/minecraft/server.properties"
    cp /opt/minecraft/server.properties .
  fi
  if [ -f "spigot-$MINECRAFT_VERSION.jar" ]
  then
    echo "spigot-$MINECRAFT_VERSION.jar exists"
  else
    echo "spigot-$MINECRAFT_VERSION.jar does not exist. Copying from /opt/minecraft/spigot-$MINECRAFT_VERSION.jar"
    cp /opt/minecraft/spigot-$MINECRAFT_VERSION.jar .
  fi
  if [ -f "eula.txt" ]
  then
    echo "eula.txt exists"
  else
    echo "eula.txt does not exist. Creating it..."
    echo "eula=true" > eula.txt
  fi
  if [ -f "ops.json" ]
  then
    echo "ops.json exists"
  else
    echo "ops.json does not exist. Copying from /opt/minecraft/ops.json"
    cp /opt/minecraft/ops.json .
  fi
else
  echo "Error: Directory /minecraft does not exists. Aborting /deploy."
fi